In [30]:

temps_list = [72, 75, 68, 71, 74, 69, 73]
import numpy as np
temps_array = np.array([72, 75, 68, 71, 74, 69, 73])
print(temps_array)
print(type(temps_array))


[72 75 68 71 74 69 73]
<class 'numpy.ndarray'>


In [29]:

sensor_temps = np.array([
 [72, 70, 71],
 [75, 73, 74],
 [68, 67, 69],
 [71, 70, 72],
 [74, 72, 73]
])
print(sensor_temps)
print(f"Shape: {sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
Shape: (5, 3)


In [ ]:
zeros = np.zeros((5, 3))
ones = np.ones((5, 3))
identity = np.eye(3)
sequence = np.arange(0, 10, 2)
linspace = np.linspace(0, 100, 5)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [ ]:
arr = np.array([1.5, 2.7, 3.2])
print(arr.dtype)

float64


In [ ]:
arr = np.array([1,2,3])
print(arr.itemsize)

8


In [ ]:
crops = np.array(['corn', 'wheat', 'soy', 'barley', 'oats'])
print(crops[0])
print(crops[-1])
print(crops[1:4])
print(crops[::2])

corn
oats
['wheat' 'soy' 'barley']
['corn' 'soy' 'oats']


In [ ]:

ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])
print(ph_levels[1, 2])
print(ph_levels[0, :])
print(ph_levels[:, 3])


6.9
[6.5 6.8 6.3 6.7]
[6.7 7.2 6.3]


In [ ]:
import numpy as np

# Defining ph_levels which was missing in this context
ph_levels = np.array([
 [6.5, 6.8, 6.3, 6.7],
 [7.1, 7.0, 6.9, 7.2],
 [6.2, 6.4, 6.1, 6.3]
])

sub_array = ph_levels[0:2, 0:3]
print("Sub-array (first 2 rows, first 3 columns):")
print(sub_array)
print("\nEvery second row:")
print(ph_levels[::2, :])

Sub-array (first 2 rows, first 3 columns):
[[6.5 6.8 6.3]
 [7.1 7.  6.9]]

Every second row:
[[6.5 6.8 6.3 6.7]
 [6.2 6.4 6.1 6.3]]


In [ ]:
temperatures = np.array([72, 85, 91, 68, 95, 70, 88])
hot_days = temperatures > 85
print(hot_days)
print(temperatures[hot_days])
print(temperatures[temperatures > 85])



[False False  True False  True False  True]
[91 95 88]
[91 95 88]


In [ ]:

moderate = temperatures[(temperatures >= 70) &
(temperatures <= 85)]
print(moderate)
extreme = temperatures[(temperatures > 90) |
(temperatures < 70)]
print(extreme)



[72 85 70]
[91 68 95]


In [ ]:

field_a = np.array([120, 135, 142, 128])
field_b = np.array([118, 140, 138, 132])
total_yield = field_a + field_b
print(total_yield)
difference = field_a - field_b
print(difference)
doubled = field_a * 2
print(doubled)

[238 275 280 260]
[ 2 -5  4 -4]
[240 270 284 256]


In [ ]:

areas = np.array([100, 144, 225, 169])
sides = np.sqrt(areas)
growth = np.exp([0, 1, 2])
np.log10([10, 100, 1000])


array([1., 2., 3.])

In [ ]:
prices = np.array([19.99, 24.51, 30.25])
np.round(prices)
np.floor(prices)
np.ceil(prices)


array([20., 25., 31.])

In [ ]:
import numpy as np


if 'print' in globals() and not callable(globals()['print']):
    del print

yields = np.array([
 [120, 125, 130, 135],
 [115, 120, 122, 128],
 [130, 135, 140, 142]
])


overall_avg = np.mean(yields)
print(f"Overall Average: {overall_avg}")

field_avgs = np.mean(yields, axis=1)
print(f"Field Averages: {field_avgs}")

year_avgs = np.mean(yields, axis=0)
print(f"Year Averages: {year_avgs}")

Overall Average: 128.5
Field Averages: [127.5  121.25 136.75]
Year Averages: [121.66666667 126.66666667 130.66666667 135.        ]
